# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Calorado Software 
email: caloradosoftware@calosoft.com
description: > # this means to ignore newlines until "baseurl:"
  This Website has been copyrighted and no one is to violate the website regulations.Any misuse of the website shall be further investigated to court.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: caloradosoftware
github_username:  caloradosoftware

# Build settings
markdown: kramdown
